### ISSUE TITLE
[FR] add support for new App Attest API

### ISSUE THREAD

**Issue by daadu** [okadan/flutter_ios_device_check#1]
The package would only be complete with this feature!!

https://developer.apple.com/documentation/devicecheck

**Comment by daadu** [comment]
@okadan Any plan for working on this feature?

**Comment by okadan** [comment]
Sorry for the slow development.

I'm planning to:

1. Renew the package name from `ios_device_check` to `device_check` to support macos as well.

2. Make the API design as follows:

```dart
// equivalent to `DCDevice.current` on Apple API.
DeviceCheck.device

// equivalent to `DCAppAttestService.shared` on Apple API.
DeviceCheck.appAttestService
```

**Comment by okadan** [comment]
@daadu 

Sorry for the slow development.

I'm planning to:

1. Renew the package name from `ios_device_check` to `device_check`. (to support macos as well)

2. Make the API design as follows:

```dart
// equivalent to `DCDevice.current` on Apple API.
DeviceCheck.device

// equivalent to `DCAppAttestService.shared` on Apple API.
DeviceCheck.appAttestService
```

**Comment by daadu** [comment]
@okadan Looking forward to the development. I would love to test this plugin with my app when done.
